export enum AuditAction {
    // Auth actions
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT',
    REGISTER = 'REGISTER',
    PASSWORD_RESET = 'PASSWORD_RESET',
    PASSWORD_CHANGE = 'PASSWORD_CHANGE',
    EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
    ACCOUNT_LOCKDOWN = 'ACCOUNT_LOCKDOWN',
    EMAIL_CHANGE = 'EMAIL_CHANGE',
    TWO_FACTOR_SETUP = 'TWO_FACTOR_SETUP',
    TWO_FACTOR_VERIFICATION = 'TWO_FACTOR_VERIFICATION',

    // Waitlist actions
    SUBSCRIBE = 'SUBSCRIBE',
    UNSUBSCRIBE = 'UNSUBSCRIBE',
    UPDATE_STATUS = 'UPDATE_STATUS',

    // Profile actions
    UPDATE_PROFILE = 'UPDATE_PROFILE',
    UPDATE_SETTINGS = 'UPDATE_SETTINGS',

    // System actions
    SYSTEM_ERROR = 'SYSTEM_ERROR',
    SYSTEM_WARNING = 'SYSTEM_WARNING',
}

export enum AuditStatus {
    SUCCESS = 'SUCCESS',
    FAILURE = 'FAILURE',
    PENDING = 'PENDING',
}
