export enum AuditAction {
    // System actions
    SYSTEM_INFO = 'SYSTEM_INFO',
    SYSTEM_WARNING = 'SYSTEM_WARNING',
    SYSTEM_ERROR = 'SYSTEM_ERROR',
    
    // Authentication actions
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT',
    REGISTER = 'REGISTER',
    PASSWORD_CHANGE = 'PASSWORD_CHANGE',
    PASSWORD_RESET = 'PASSWORD_RESET',
    EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
    TWO_FACTOR_SETUP = 'TWO_FACTOR_SETUP',
    TWO_FACTOR_VERIFICATION = 'TWO_FACTOR_VERIFICATION',
    
    // Waitlist actions
    SUBSCRIBE = 'SUBSCRIBE',
    UNSUBSCRIBE = 'UNSUBSCRIBE',
    INVITE = 'INVITE',
    
    // User actions
    PROFILE_UPDATE = 'PROFILE_UPDATE',
    
    // Dashboard access
    DASHBOARD_ACCESS = 'DASHBOARD_ACCESS',
    
    // Feature requests
    FEATURE_REQUEST_CREATE = 'FEATURE_REQUEST_CREATE',
    FEATURE_REQUEST_UPDATE = 'FEATURE_REQUEST_UPDATE',
    
    // Custom action
    CUSTOM = 'CUSTOM'
}

export enum AuditStatus {
    SUCCESS = 'SUCCESS',
    FAILURE = 'FAILURE',
    WARNING = 'WARNING',
    INFO = 'INFO'
}
